language: "en-US"
early_access: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: true
chat:
  auto_reply: true
